---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    app: simple-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: simple-app-port
  selector:
    app: simple-app